"""Modular OCR pipeline scaffolding."""

from .input_handler import BasicInputHandler
from .interfaces import (
    Aggregator,
    DocumentOcrPipeline,
    InputHandler,
    OcrPipeline,
    RegionClassifier,
    Segmenter,
    TableExtractor,
    TextOCR,
    VLLM,
)
from .mocks import (
    MockAggregator,
    MockInputHandler,
    MockRegionClassifier,
    MockSegmenter,
    MockTableExtractor,
    MockTextOCR,
    MockVLLM,
)
from .models import (
    BoundingBox,
    ClassifiedRegion,
    DocumentInput,
    DocumentMetadata,
    DocumentOutput,
    ImageCaptionResult,
    PageInput,
    RegionOutput,
    RegionType,
    SegmentedRegion,
    StructuralEdge,
    StructuralGraph,
    StructuralNode,
    TableData,
    TableExtractionResult,
    TextOcrResult,
)
from .structure import (
    build_structural_graph,
    graph_from_jsonld,
    graph_to_jsonld,
    graph_to_llm_prompts,
    graph_to_tool_calls,
    load_jsonld,
    save_jsonld,
)
from .pipeline import DocumentPipeline, OcrPipeline
from .simple import (
    AspectRatioRegionClassifier,
    DummyTableExtractor,
    DummyVLLM,
    FullPageSegmenter,
    SimpleAggregator,
    SimpleTableExtractor,
    SimpleVLLM,
)
from .hybrid import ToyRuntimeTextOCR, TwoStageTextOCR
from .tesseract import TesseractTextOCR

__all__ = [
    "Aggregator",
    "BasicInputHandler",
    "BoundingBox",
    "ClassifiedRegion",
    "DocumentOcrPipeline",
    "DocumentInput",
    "DocumentMetadata",
    "DocumentOutput",
    "ImageCaptionResult",
    "InputHandler",
    "MockAggregator",
    "MockInputHandler",
    "MockRegionClassifier",
    "MockSegmenter",
    "MockTableExtractor",
    "MockTextOCR",
    "MockVLLM",
    "FullPageSegmenter",
    "AspectRatioRegionClassifier",
    "SimpleAggregator",
    "SimpleTableExtractor",
    "SimpleVLLM",
    "DummyVLLM",
    "DummyTableExtractor",
    "ToyRuntimeTextOCR",
    "TwoStageTextOCR",
    "OcrPipeline",
    "DocumentPipeline",
    "PageInput",
    "RegionClassifier",
    "RegionOutput",
    "RegionType",
    "SegmentedRegion",
    "StructuralEdge",
    "StructuralGraph",
    "StructuralNode",
    "Segmenter",
    "TableData",
    "TableExtractionResult",
    "TableExtractor",
    "TesseractTextOCR",
    "TextOCR",
    "TextOcrResult",
    "VLLM",
    "build_structural_graph",
    "graph_from_jsonld",
    "graph_to_jsonld",
    "graph_to_llm_prompts",
    "graph_to_tool_calls",
    "load_jsonld",
    "save_jsonld",
]
